mysql:
  host: 192.168.0.108
  port: 3306
  db: gvb_db
  user: PipelineCN
  password: admin@2023
  log_level: dev

system:
  host: 0.0.0.0
  port: 8080
  env: dev

logger:
  level: info
  prefix: "[gvb]"
  director: log
  show_line: true
  log_in_console:


